services:
  api:
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile-Api"
    container_name: "api"
    environment:
      API_TOKEN: ${API_TOKEN}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      LW_API_20_CLIENT_ID: ${LW_API_20_CLIENT_ID}
      LW_API_20_CLIENT_SECRET: ${LW_API_20_CLIENT_SECRET}
      LW_API_20_SERVICE_ACCOUNT_ID: ${LW_API_20_SERVICE_ACCOUNT_ID}
      PHOTO_ID_OPEN: ${PHOTO_ID_OPEN}
      PHOTO_ID_CLOSE: ${PHOTO_ID_CLOSE}
    volumes:
      - ./:/app/
    working_dir: "/app/"
    tty: true
    networks:
      - app-birn-net
  yoru:
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile-Yoru"
    depends_on:
      api:
        condition: service_started
    container_name: "yoru"
    environment:
      API_TOKEN: ${API_TOKEN}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      VIDEO_PATH: ${VIDEO_PATH}
    volumes:
      - ./:/app/
    working_dir: "/app/"
    tty: true
    networks:
      - app-birn-net

networks:
  app-birn-net:
    driver: bridge
